# This file was generated by GoReleaser. DO NOT EDIT.
cask "pleno-dlp" do
  version "0.66.1"

  on_macos do
    on_arm do
      sha256 "2d25c8245165a0355c0bd5fcf2f03fc961ccff69c4f96076fd11aaca9700a224"
      url "https://github.com/plenoai/pleno-dlp/releases/download/v#{version}/pleno-dlp_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0d12042764e2ddb9ee6489cbdce781c382cdaae8d1c8ec5b3970f59890d129a0"
      url "https://github.com/plenoai/pleno-dlp/releases/download/v#{version}/pleno-dlp_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d71f62b24bfbe3dfef1bdb0d7a02eb10fc4ea1013b1b3704dedbcc6ad366d5a6"
      url "https://github.com/plenoai/pleno-dlp/releases/download/v#{version}/pleno-dlp_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2db068ff32820c9e14bfa8ee86d33dd6f6a9a2865d6db24847c9cb97239f713c"
      url "https://github.com/plenoai/pleno-dlp/releases/download/v#{version}/pleno-dlp_linux_amd64.tar.gz"
    end
  end

  name "pleno-dlp"
  desc "Unified DLP scanner for secrets and PII across filesystem, git, stdin, and SaaS sources."
  homepage "https://plenoai.com/pleno-dlp/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pleno-dlp"

  # No zap stanza required
end
