# This file was generated by GoReleaser. DO NOT EDIT.
cask "pleno-dlp" do
  version "0.64.5"

  on_macos do
    on_intel do
      sha256 "078712a3800b36b40bf8c068c77088d6c032f666c381f466207370c75f39e651"
      url "https://github.com/plenoai/pleno-dlp/releases/download/v#{version}/pleno-dlp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c1eb13f575d7637d2fbf26af426400818b3e9656ef2763a413e001db80e9a738"
      url "https://github.com/plenoai/pleno-dlp/releases/download/v#{version}/pleno-dlp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0d48a903db11850df709e906548b55988dd33a749fa1c5c13098af369bc88f32"
      url "https://github.com/plenoai/pleno-dlp/releases/download/v#{version}/pleno-dlp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9957f575520dd74b85fad1907b0c662d9a794483e37b41b99c8aa6e512b37e6a"
      url "https://github.com/plenoai/pleno-dlp/releases/download/v#{version}/pleno-dlp_linux_arm64.tar.gz"
    end
  end

  name "pleno-dlp"
  desc "Unified DLP scanner for secrets and PII across filesystem, git, stdin, and SaaS sources."
  homepage "https://plenoai.com/pleno-dlp/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pleno-dlp"

  # No zap stanza required

end
