# This file was generated by GoReleaser. DO NOT EDIT.
cask "pleno-dlp" do
  version "0.66.3"

  on_macos do
    on_arm do
      sha256 "4d1d75c57728184293cbd4499a199bc9f1c91391f501f3b7955b7fc89ffdad56"
      url "https://github.com/plenoai/pleno-dlp/releases/download/v#{version}/pleno-dlp_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "465edf321b1c1ab938596a4144cdab3d5252443f7af04d200e188c73ffde8018"
      url "https://github.com/plenoai/pleno-dlp/releases/download/v#{version}/pleno-dlp_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "73f62311435ec0d018bf8a0c21c1c19f585cd82c52e951911d3b9a5526acc536"
      url "https://github.com/plenoai/pleno-dlp/releases/download/v#{version}/pleno-dlp_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "48ef47629da51c48283348425c708646deca376e66084b21c2a6f3c62838267e"
      url "https://github.com/plenoai/pleno-dlp/releases/download/v#{version}/pleno-dlp_linux_amd64.tar.gz"
    end
  end

  name "pleno-dlp"
  desc "Unified DLP scanner for secrets and PII across filesystem, git, stdin, and SaaS sources."
  homepage "https://plenoai.com/pleno-dlp/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pleno-dlp"

  # No zap stanza required
end
