# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlenoDlp < Formula
  desc "Unified DLP scanner for secrets and PII across filesystem, git, stdin, and SaaS sources."
  homepage "https://plenoai.com/pleno-dlp/"
  version "0.61.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/plenoai/pleno-dlp/releases/download/v0.61.0/pleno-dlp_darwin_amd64.tar.gz"
      sha256 "bb5f2923bd8442b03b0a30cb7348ff9e969485529076ab40b0fdcccbc4a27fa2"

      define_method(:install) do
        bin.install "pleno-dlp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/plenoai/pleno-dlp/releases/download/v0.61.0/pleno-dlp_darwin_arm64.tar.gz"
      sha256 "340972839e2cd7d3a33a0b2a7ec1ab6323c1bb070cc52f1c994760e0a9d288c3"

      define_method(:install) do
        bin.install "pleno-dlp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/plenoai/pleno-dlp/releases/download/v0.61.0/pleno-dlp_linux_amd64.tar.gz"
      sha256 "00987ebafe6548d536862cf6808288e0299b422bfa817901e5c45a947d2404a6"
      define_method(:install) do
        bin.install "pleno-dlp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/plenoai/pleno-dlp/releases/download/v0.61.0/pleno-dlp_linux_arm64.tar.gz"
      sha256 "9abdd43933ba6ed325954de49a635117847f4a0204f4ed5d9eb7d9a982f863d6"
      define_method(:install) do
        bin.install "pleno-dlp"
      end
    end
  end

  test do
    system "#{bin}/pleno-dlp", "--version"
  end
end
