# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlenoDlp < Formula
  desc "Unified DLP scanner for secrets and PII across filesystem, git, stdin, and SaaS sources."
  homepage "https://plenoai.com/pleno-dlp/"
  version "0.60.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/plenoai/pleno-dlp/releases/download/v0.60.0/pleno-dlp_darwin_amd64.tar.gz"
      sha256 "4bb3ae76223f5b2324258def404bcb5c48ab2f92aae35c31c09ed5eb89479732"

      define_method(:install) do
        bin.install "pleno-dlp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/plenoai/pleno-dlp/releases/download/v0.60.0/pleno-dlp_darwin_arm64.tar.gz"
      sha256 "7fa9a8416b21944cd2172596d250fbf0629b883b9cfec2d2fcb080dfe2cd9daa"

      define_method(:install) do
        bin.install "pleno-dlp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/plenoai/pleno-dlp/releases/download/v0.60.0/pleno-dlp_linux_amd64.tar.gz"
      sha256 "8e5bcb3e31976fa8b37a8ba2f61c604f136be38549dd50820bcbcfc8c578576e"
      define_method(:install) do
        bin.install "pleno-dlp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/plenoai/pleno-dlp/releases/download/v0.60.0/pleno-dlp_linux_arm64.tar.gz"
      sha256 "9f032ff2678e45f941d7449e1afa38a4a5d3e0d4fc79414665ee788b0b9b10fc"
      define_method(:install) do
        bin.install "pleno-dlp"
      end
    end
  end

  test do
    system "#{bin}/pleno-dlp", "--version"
  end
end
