# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlenoDlp < Formula
  desc "Unified DLP scanner for secrets and PII across filesystem, git, stdin, and SaaS sources."
  homepage "https://plenoai.com/pleno-dlp/"
  version "0.62.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/plenoai/pleno-dlp/releases/download/v0.62.0/pleno-dlp_darwin_amd64.tar.gz"
      sha256 "5ccf2bae4ca8e78fcf16f771d7a047054a2ea1b64b8470b35bdd5e1abc7e9445"

      define_method(:install) do
        bin.install "pleno-dlp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/plenoai/pleno-dlp/releases/download/v0.62.0/pleno-dlp_darwin_arm64.tar.gz"
      sha256 "fce098c0306ce6fb41bc238a291f0ac7209087afbd06be7f7964497e6ffd3257"

      define_method(:install) do
        bin.install "pleno-dlp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/plenoai/pleno-dlp/releases/download/v0.62.0/pleno-dlp_linux_amd64.tar.gz"
      sha256 "96a0fe3d034aaa9f3b6006564da62bf4b0335d092d8f33b9ff4b24104094e422"
      define_method(:install) do
        bin.install "pleno-dlp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/plenoai/pleno-dlp/releases/download/v0.62.0/pleno-dlp_linux_arm64.tar.gz"
      sha256 "aaeede5305e1e733d343266e12f6f78064ee6b434f471b15dea0230009ee42fb"
      define_method(:install) do
        bin.install "pleno-dlp"
      end
    end
  end

  test do
    system "#{bin}/pleno-dlp", "--version"
  end
end
